# -*- mode: ruby -*-
# vim: set ft=ruby :
##############################################################################################################

MACHINES = {
  :inetRouter => {
        :box_name => "centos/7",
        :vm_name => "inetRouter",
        :net => [
                  {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net1"},
                  {ip: '192.168.255.3', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
                  {ip: '192.168.56.10', adapter: 8},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :vm_name => "centralRouter",
        :net => [
                  {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net1"},
                  {ip: '192.168.101.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net1"},
                  {ip: '192.168.56.11', adapter: 8},
                ]
  },
  :centralServer => {
        :box_name => "centos/7",
        :vm_name => "centralServer",
        :net => [
                  {ip: '192.168.101.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net1"},
                  {ip: '192.168.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "net1"},
                  {ip: '192.168.56.12', adapter: 8},
                ]
  },
  :centralRouter2 => {
        :box_name => "centos/7",
        :vm_name => "centralRouter2",
        :net => [
                  {ip: '192.168.255.4', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
                  {ip: '192.168.102.1', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "dir-net2"},
                  {ip: '192.168.56.21', adapter: 8},
                ]
  },
  :centralServer2 => {
        :box_name => "centos/7",
        :vm_name => "centralServer2",
        :net => [
                  {ip: '192.168.102.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net2"},
                  {ip: '192.168.20.1', adapter: 5, netmask: "255.255.255.0", virtualbox__intnet: "net2"},
                  {ip: '192.168.56.22', adapter: 8},
                ]
  },
}

##############################################################################################################

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      if boxconfig[:vm_name] == "centralServer2"
        box.vm.provision "ansible" do |ansible|
          ansible.playbook = "ansible/provision.yml"
          ansible.inventory_path = "inventory/hosts"
          ansible.host_key_checking = "false"
          ansible.limit = "all"
        end
      end
      boxconfig[:net].each do |ipconf|
      box.vm.network "private_network", ipconf
    end
    if boxconfig.key?(:public)
      box.vm.network "public_network", boxconfig[:public]
    end
    box.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    end
  end
end

##############################################################################################################
