version: '3'
services:
    nginx:
        build: ./images/nginx
        ports:
            - "80:80"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - php
        depends_on:
            - php
    php:
        build: ./images/php
        volumes:
            - ./www:/var/www

