nodes = [
	{ :hostname => 'centos-web', :ip => '192.168.56.10', :memory => 1024, :cpu => 1, :boxname => "centos/7" },
	{ :hostname => 'centos-log', :ip => '192.168.56.20', :memory => 1024, :cpu => 1, :boxname => "centos/7" },
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
      config.vm.box_check_update = false
      config.vm.define node[:hostname] do |nodeconfig|
          nodeconfig.vm.box = node[:boxname]
	  nodeconfig.vm.hostname = node[:hostname]
	  nodeconfig.vm.network :private_network, ip: node[:ip]
	  nodeconfig.vm.provider :virtualbox do |vb|
	    vb.memory = node[:memory]
            vb.cpus = node[:cpu]
	  end
	  nodeconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
          end
      end
  end
end

