# -*- mode: ruby -*-
# vi: set ft=ruby :
# export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|

  config.vm.box = 'centos/7'

  config.vm.define "server" do |server|
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
  end

  server.vm.host_name = 'rpm-repo'
  server.vm.network :private_network, ip: "192.168.56.15"

  server.vm.provision "shell",
    name: "configuration",
    path: "init_srv.sh"

  end

end
